// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvhk5Xm5gZ9niInWcyiZ_Or9ckTukp4aU',
    appId: '1:381003064522:web:3d1f67a85df7775e64c033',
    messagingSenderId: '381003064522',
    projectId: 'week-3-verif',
    authDomain: 'week-3-verif.firebaseapp.com',
    storageBucket: 'week-3-verif.firebasestorage.app',
    measurementId: 'G-MLRJ1THFLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdOd_uGidx6JqdL-sH-hsobtYkA0SoVGw',
    appId: '1:381003064522:android:608f0f0e221624e364c033',
    messagingSenderId: '381003064522',
    projectId: 'week-3-verif',
    storageBucket: 'week-3-verif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcic_jD96wdFBHCgzhhKMmNJ2htLmY6MQ',
    appId: '1:381003064522:ios:a87ccf5e6dc273c264c033',
    messagingSenderId: '381003064522',
    projectId: 'week-3-verif',
    storageBucket: 'week-3-verif.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvhk5Xm5gZ9niInWcyiZ_Or9ckTukp4aU',
    appId: '1:381003064522:web:803b75683ea0d4aa64c033',
    messagingSenderId: '381003064522',
    projectId: 'week-3-verif',
    authDomain: 'week-3-verif.firebaseapp.com',
    storageBucket: 'week-3-verif.firebasestorage.app',
    measurementId: 'G-1FQNM4LJ7F',
  );
}
